version: "3"
services:
  backend:
    build: ./backend
    env_file: backend/.env
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/database:/opt/app/database
      - ./backend/public:/opt/app/public
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/package-lock.json:/opt/package-lock.json
      - ./backend/tsconfig.json:/opt/tsconfig.json
      - ./backend/.env:/opt/app/.env
    ports:
      - "1337:1337"
  frontend:
    image: node:16-alpine
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    command: sh -c "npm run dev || npm ci"
    ports:
      - "3000:3000"
    user: node
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
