version: "3"
services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile.prod
    env_file: backend/.env
    volumes:
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    expose:
      - 1337
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.prod
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    expose:
      - 3000
  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - frontend
    image: nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-9000}:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
