version: "3"
services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: backend/.env
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/package-lock.json:/opt/package-lock.json
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    expose:
      - 1337
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.prod
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    command: sh -c "npm run dev || npm ci"
    expose:
      - 3000
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - frontend
    image: nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-9000}:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
