fragment CartFragment on Cart {
	id
	checkoutUrl
	cost {
		subtotalAmount {
			amount
			currencyCode
		}
		totalAmount {
			amount
			currencyCode
		}
	}
	totalQuantity
	lines(first: 100) {
		edges {
			node {
				id
				quantity
				cost {
					amountPerQuantity {
						amount
						currencyCode
					}
					subtotalAmount {
						amount
						currencyCode
					}
					totalAmount {
						amount
						currencyCode
					}
				}
				merchandise {
					... on ProductVariant {
						id
						title
						product {
							title
						}
						quantityAvailable
						selectedOptions {
							name
							value
						}
						image {
							height
							url
							width
						}
						price {
							amount
							currencyCode
						}
					}
				}
			}
		}
	}
}
