query Artworks($start: Int = 0) {
	artworks(sort: "id:desc", pagination: { start: $start, limit: 10 }) {
		data {
			attributes {
				name
				image {
					data {
						attributes {
							...UploadFile
						}
					}
				}
				description
				external_link
			}
		}
		meta {
			pagination {
				total
				page
				pageSize
				pageCount
			}
		}
	}
}

fragment UploadFile on UploadFile {
	name
	alternativeText
	caption
	width
	height
	hash
	ext
	formats
}
