#import "./fragments/UploadFile.fragment.gql"

query ArtworkBySlug($slug: String!) {
	artwork(slug: $slug) {
		data {
			attributes {
				name
				description
				image {
					data {
						attributes {
							...UploadFile
						}
					}
				}
				redbubble_link
				original_sold
				slug
				year_of_creation
				width
				height
				medium
				sections {
					__typename
					... on ComponentSectionsRichText {
						text
					}
					... on ComponentSectionsTextWithPicture {
						twp_picture_alignment: picture_alignment
						text
						image {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
					... on ComponentSectionsCallToAction {
						title
						text
						cta_picture_alignment: picture_alignment
						link {
							label
							path
						}
						image {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
					... on ComponentSectionsShowcase {
						images {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
				}
			}
		}
	}
	artworks(
		sort: "updatedAt:desc"
		pagination: { pageSize: 4 }
		filters: { name: { ne: $slug } }
	) {
		data {
			attributes {
				name
				slug
				image {
					data {
						attributes {
							...UploadFile
						}
					}
				}
			}
		}
	}
}
