query GeneralInformation {
	meta {
		data {
			attributes {
				page_prefix
				metatags {
					content
					name
					property
				}
			}
		}
	}
	pageInformation {
		data {
			attributes {
				cookie_consent_text
				legal {
					label
					path
				}
				links {
					label
					path
				}
				socials {
					link
					type
				}
			}
		}
	}
}
