#import "./fragments/UploadFile.fragment.gql"

query Meta {
	meta {
		data {
			attributes {
				title
				page_prefix
				description
				favicon {
					data {
						attributes {
							...UploadFile
						}
					}
				}
			}
		}
	}
}
