#import "./fragments/UploadFile.fragment.gql"

query PageBySlug($slug: String!) {
	page(slug: $slug) {
		data {
			attributes {
				title
				slug
				accessibility {
					title
					description
					image {
						data {
							attributes {
								...UploadFile
							}
						}
					}
				}
				sections {
					__typename
					... on ComponentSectionsRichText {
						text
					}
					... on ComponentSectionsCallToAction {
						type
						text
						image_alignment
						link {
							label
							path
						}
						image {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
					... on ComponentSectionsShowcase {
						images {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
				}
			}
		}
	}
}
