#import "./fragments/UploadFile.fragment.gql"

query PageInformation {
	pageInformation {
		data {
			attributes {
				cookie_consent_text
				legal {
					label
					path
				}
				links {
					label
					path
				}
				logo {
					data {
						attributes {
							...UploadFile
						}
					}
				}
				socials {
					link
					type
				}
			}
		}
	}
}
