#import "./fragments/UploadFile.fragment.gql"

query Startpage {
	startPage {
		data {
			attributes {
				title
				foreground {
					data {
						attributes {
							...UploadFile
						}
					}
				}
				background {
					data {
						attributes {
							...UploadFile
						}
					}
				}
				seo {
					title
					description
					image {
						data {
							attributes {
								...UploadFile
							}
						}
					}
				}
				sections {
					__typename
					... on ComponentSectionsRichText {
						text
					}
					... on ComponentSectionsCallToAction {
						type
						text
						image_alignment
						link {
							label
							path
						}
						image {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
					... on ComponentSectionsShowcase {
						images {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
				}
			}
		}
	}
}
