#import "./fragments/UploadFile.fragment.gql"

query Startpage {
	startPage {
		data {
			attributes {
				title
				background {
					data {
						attributes {
							...UploadFile
						}
					}
				}
				sections {
					__typename
					... on ComponentSectionsArtworkDisplay {
						title
						artworks {
							data {
								attributes {
									name
									slug
									image {
										data {
											attributes {
												...UploadFile
											}
										}
									}
								}
							}
						}
					}
					... on ComponentSectionsRichText {
						text
					}
					... on ComponentSectionsTextWithPicture {
						twp_picture_alignment: picture_alignment
						text
						image {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
					... on ComponentSectionsCallToAction {
						title
						text
						cta_picture_alignment: picture_alignment
						link {
							label
							path
						}
						image {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
					... on ComponentSectionsShowcase {
						images {
							data {
								attributes {
									...UploadFile
								}
							}
						}
					}
				}
			}
		}
	}
}
