mutation AddToCart($cartId: ID!, $lines: [CartLineInput!]!) {
	cartLinesAdd(cartId: $cartId, lines: $lines) {
		cart {
			id
			createdAt
			updatedAt
			checkoutUrl
			totalQuantity
			lines(first: 10) {
				edges {
					node {
						id
						quantity
						merchandise {
							... on ProductVariant {
								id
							}
						}
					}
				}
			}
			cost {
				totalAmount {
					amount
					currencyCode
				}
				subtotalAmount {
					amount
					currencyCode
				}
				totalTaxAmount {
					amount
					currencyCode
				}
				totalDutyAmount {
					amount
					currencyCode
				}
			}
		}
	}
}
