query GetCartPreview($id: ID!) {
	cart(id: $id) {
		id
		totalQuantity
		lines(first: 100) {
			edges {
				node {
					id
					quantity
					merchandise {
						... on ProductVariant {
							id
						}
					}
				}
			}
		}
	}
}
