#import "../fragments/ImageWithPreview.fragment.gql"
query Products {
	products(first: 250, sortKey: UPDATED_AT, reverse: true) {
		edges {
			node {
				id
				title
				handle
				description
				descriptionHtml
				productType
				featuredImage {
					...ImageWithPreview
				}
			}
		}
	}
}
