#import "../fragments/ImageWithPreview.fragment.gql"

query Products {
	products(first: 10) {
		edges {
			node {
				id
				title
				handle
				description
				descriptionHtml
				featuredImage {
					...ImageWithPreview
				}
			}
		}
	}
}
