query Products {
	products(first: 10) {
		edges {
			node {
				id
				title
				handle
				description
				descriptionHtml
				featuredImage {
					altText
					height
					url
					width
				}
			}
		}
	}
}
