mutation UpdateCart($cartId: ID!, $lines: [CartLineUpdateInput!]!) {
	cartLinesUpdate(cartId: $cartId, lines: $lines) {
		cart {
			id
			checkoutUrl
			cost {
				subtotalAmount {
					amount
					currencyCode
				}
				totalAmount {
					amount
					currencyCode
				}
			}
			lines(first: 10) {
				edges {
					node {
						id
						quantity
						merchandise {
							... on ProductVariant {
								id
								title
								product {
									title
								}
								quantityAvailable
								selectedOptions {
									name
									value
								}
								image {
									height
									url
									width
								}
								price {
									amount
									currencyCode
								}
							}
						}
					}
				}
			}
		}
	}
}
